### ISSUE TITLE
Please do not modify the API interface

### ISSUE THREAD

**Issue by KumaWang** [KilledByAPixel/LittleJS#101]
We have a game IDE that uses littlejs as the engine. In the new version, you have modified the keycode and some of our functions cannot be used. If possible, please make the update compatible with the old version of the interface.
![image](https://github.com/user-attachments/assets/ef01ce3c-edac-440e-8d30-9bafeaca6fa8)
![image](https://github.com/user-attachments/assets/f0973edb-9b2b-435f-8fd1-bdc6403332e9)

**Comment by KilledByAPixel** [comment]
Wow, that looks amazing! I apologize if any of these updates effect your progress. I had been working on making sure the engine is fully modern compliant, and now that it is I don't anticipate any other major API changes.

Usually I try to never modify the API but occasionally there is an improvement necessary that requires a small change. In this case using the key code numerical value has been deprecated for years, and a few people asked me to change it because the improved way of handling the physical keyboard layout.

I understand you are making an IDE, which can make the fix more challenging. I've had to deal with some incredibly difficult Unreal Engine 4 merges before with at a huge company with multiple projects where we made too many custom engine modifications. So trust me, I know where you are coming from!

If you have any questions at all while working with the engine feel free ask. [The LittleJS discord](https://discord.gg/zb7hcGkyZe) is probably the best place to post. I am happy to help with any integration issues you may have. Can't wait to see what you make!

**Comment by KumaWang** [comment]
I think you could replace the keycodes with something like an int enum, i guessing you've thought about it, but this is more friendly to IDE code auto-completion.
[keys.txt](https://github.com/user-attachments/files/16570954/keys.txt)

**Comment by KumaWang** [comment]
and can I join your team?

**Comment by KilledByAPixel** [comment]
You can still use that same enum, just replace the numbers with strings that the key corresponds to. Creating an enum like that is good practice and should help with changing it over.

**Comment by KumaWang** [comment]
thank you ~
