### ISSUE TITLE
Drawing polygons and circles

### ISSUE THREAD

**Issue by patrickgh3** [KilledByAPixel/LittleJS#118]
Hello. I've been making my second game using LittleJS and have been really enjoying the engine! :)

I wanted to draw a polygon in my game. I saw that there was no function for this (I believe). So, I inserted my own code into the debugRender function to draw my polygon using overlayContext.beginPath() and related functions, and that worked great! (With the exception that I had to fiddle with multiplying some coordinates by -1 to draw the polygon non-flipped.)

I have two questions:

1. Is my approach of inserting my code into debugRender reasonable and intended? Or perhaps is there a cleaner way for me to do it, or a cleaner way could be added?

2. Is there a reason that polygon and circle drawing functions are not provided by the engine? Perhaps there is a good reason, such as maybe those primitives being non-trivial to support using OpenGL, or wanting to keep the engine's feature set minimal. Personally, drawing circles and polygons is frequently something I want to do when making games using tools like Raylib, which is why I was a little bit surprised these functions didn't exist in LittleJS.

Thank you!

**Comment by KilledByAPixel** [comment]
You should not be modifying the debugRender function, that is used internally for the debug functionality. The debug stuff is really only intended for debugging, not for anything that would be in your final game.

[I just pushed an small update to GitHub for you with 3 new functions: drawPoly, drawCircle, and drawEllipse.](https://github.com/KilledByAPixel/LittleJS/blob/fb13034f6ddcb9defe8f4083fa727b8271eb8031/src/engineDraw.js#L295)

These functions were not included because they are standard canvas context functions and much slower then using the webgl rendering system. Also, they are drawn to the 2d canvas rather then the webgl canvas like the sprites.

For drawing circles or ellipse rendering I always just use a circle texture. We can implement a separate webgl pipeline for drawing polygons at some point but it hasn't really been necessary. It is something to think about though as we continue to grow the engine.

Let me know if those functions work ok for you!

**Comment by patrickgh3** [comment]
Thanks a bunch for the very prompt answer and implementation! I've just recompiled LittleJS with the new drawPoly function, tweaked my code to use it within the gameRender function, and it works perfectly for me! It was a very quick drop-in replacement. I also briefly tested out drawCircle and drawEllipse in world space, and they work fine for me too.

For further context, my game only draws 1 polygon each frame, which has a couple hundred points. It's a graph of play activity over time that's displayed to the player. So, I think this is okay performance-wise. It's very handy to have this function in the future too for any more one-off polygons I might need.

Thank you! :)
