### ISSUE TITLE
Redrawing a single tileData after changing its data

### ISSUE THREAD

**Issue by slosumo** [KilledByAPixel/LittleJS#14]
While this is a more complex use case, I could imagine it be useful to a lot, to be able to do animations on tiles when needed, and use tilelayer rendering for them whenever possible for best performance.

TLDR: I'm wondering if it's possible to change data of a tileLayer and redraw just that tile, instead of the whole layer (clearing works, but not redrawing, because of the assert check in drawTileData)

While I could just remove the assert that feels wrong, but so does redrawing the whole layer. Is there something you'd suggest doing here? If this could be done without breaking "the laws of littlejs", it would be an amazing performance improvement to run a ton of temporary animations on tiles when needed

Below is my code, which I intend to later use for basically doing animations on tiles (where I'll temporarily unset tile data, and render animation on the mainContext instead, then when animation ends, fallback to using tileData), but currently I'm just trying to get this working:

```
let ongoingTileAnimations = []; // stores info about any ongoing tileAnimations, which are then checked and handled every frame

function beginTileAnimation(data) {
    /* function that is used for animating stuff, i.e. if a tile has to be animated, we remove that tile from the tilelayer data,
        perform the animation in a new object we create on the mainCanvas,
        and when animation ends, we restore the original (or modified) tilelayer data at that position
     */

    /* ** signifies required params
    * Data:
    * pos/posTileIndex**
    * tileLayer**
    * animationData: duration**,
    * + any other data I might need for diff animations
    * */

    data.startedAt = realTime;
    data.endAt = realTime + data.animationData.duration;
    if (data.tileLayer) {

        data.originalTileData = tileLayers[data.tileLayer].getData(data.pos);

        tileLayers[data.tileLayer].setData(data.pos, new TileLayerData, 1); // set and clear tile
    }
    ongoingTileAnimations.push(data);
}

function processTileAnimations() { // this function is ran from gameUpdate(), and checks for any ongoing animations
    let animData;
    for(let i=ongoingTileAnimations.length-1; i >= 0; i--) {
        animData = ongoingTileAnimations[i];

        if (animData.endAt <= realTime) {
            /* for now, this examples just attempts to restore tileData after passed time, but here, the setData ASSERT error happens,
            * because the tile is attempting to render a tile, not just a color (in function drawTileData)
            */
            //console.log("animation ended here!, data: " + JSON.stringify(animData));

            tileLayers[animData.tileLayer].setData(animData.pos, animData.originalTileData, 1); // doesn't work <- assert error

            /* // this DOES work, but seems like overkill redrawing whole tileLayer
            tileLayers[animData.tileLayer].setData(animData.pos, animData.originalTileData);
            tileLayers.terrain_pri.redraw();
            */

            ongoingTileAnimations.splice(i, 1); // remove animationData
        }
    }
}
```

**Comment by KilledByAPixel** [comment]
There is a way to do this!

You must first call tileLayer.redrawStart() and at the end call tileLayer.redrawEnd(). Try to do this as little as possible because that is where you will incure the most overhead.

If you are just removing tiles it is much faster then drawing new tiles. Platformer example does something like this when you destroy the level, it calls set tile, but since it is only clearing it is not necessary to call redraw start/end.

I've pinpointed the slowness to some browsers that are slow with rendering gl canvas to 2d canvas. In theory it should be fast and chrome is plenty fast but firefox is slow for some reason.

Let me know if that works for you, I'm interested to hear about your results!

**Comment by slosumo** [comment]
I actually did try calling that as well, but then ONLY the changed tiles are rendered (any rendered between start and end), not the whole layer.

Am I missing something maybe? Anyway, I can give this a second try tomorrow :)

**Comment by slosumo** [comment]
Ahhh! maybe I should call redrawStart(0) as it clear it by default! Will let you know tomorrow

**Comment by KilledByAPixel** [comment]
Yes that's it. I will change the default for redrawStart to 0, i think that is more clear.

Just discovered a major speed bump! The slowdown from this is caused by changing the gl canvas size 

`glContext.viewport(0, 0, glCanvas.width = width, glCanvas.height = height);`

That happens when the level is redrawn which I assume causes the texture to be rebuilt which is slow. Working on a fix now that will be much faster.

**Comment by slosumo** [comment]
Yeah I think that might be a bit clearer indeed. That's good to hear!

On that note -> clearing canvases with
ctx.clearRect(0,0, canvas.width, canvas.height)
is supposed to be faster than
canvas.width = width;
canvas.height = height;

Not sure if that'll amount to much, but I've seen that you've been using this in a few places.

**Comment by KilledByAPixel** [comment]
Just investigated a bit more and it is more complicated then I thought. It would be much faster to have a separate gl canvas and context for each tile layer. The problem is, that since it is a different context, it also needs it's own shader, texture and stuff. It's not that big of a deal, just a bunch of stuff needs to be reworked. Might be worth it for the perf benefit. I will have a think on it.

**Comment by slosumo** [comment]
Sounds like an interesting option - but definitely don't prioritize this -> you've got other more important priority tasks that will be useful to more for sure :)
