### ISSUE TITLE
Direction angle for particle emitter

### ISSUE THREAD

**Issue by slosumo** [KilledByAPixel/LittleJS#20]
1) I've spent a bit too much time than I'd like on this, figuring out how I can set the direction where the particle emmiter emits to, trying out all different combinations of params. Only to find out, I can easily do it by setting the particleEmitter.angle  after creating it.

Unless you dive into the code this is really unclear - imo it would make a lot of sense to add another clear parameter for "emitAngle" that allows users to easily control use.

2) To add onto this, the current particles can only be of square shape -> unless if I used a tile image that was of rectangular shape. But if I want to just use colored particles that are shaped like a rectangle, it's not currently possible. Am I thinking in "the wrong way again", and there's no reason for this to be added, and I should just make a rectangular tile and use that one?

**Comment by KilledByAPixel** [comment]
1.

Sorry for the confusion! This is how particle emitters works in pretty much every engine, 3d or otherwise. You set the orientation of the emitter object to control the direction of the particles. In this case that is the angle of the emitter object.

You can also attach the emitter to another object as a child.

Adding an extra parameter emitAngle would be bad and more confusing because then what does the emitter.angle do?

I will get to the particle emitter editor soon that will help with this. It will work like zzfx but output parameters for the particle system to use.

2. 

Particles are square in almost all game engines. You can make them non square by changing the image to a rectangle inside the square shape like you suggest. You can apply color to any particles, texture or not. Have you tried it?

**Comment by slosumo** [comment]
1. Definitely don't change things out of the common practice just because I'm confused or have specific use-cases :D I just try to give you the honest/stupid feedback as I think is the best sort, especially if you'll try to make the engine more approachable to the masses.

I didn't really mean for emitAngle to replace emitter.angle, but more be just a parameter to be able to pass, that does:
this.angle = emitAngle; // maybe just passing "angle" then would make more sense

Just think it could be convenient in some use cases as you're currently passing it as undefined always. But if it's not good practice, no need :) Sounds great on the editor, will be very helpful!

2) I'm away of how to apply color, but was i.e. just looking to be able to easily create a circle or rectangular particle of a color, WITHOUT the need of having to have a texture for it. Right now if wanting to do either you'd have to have a image for it - which is NOT a huge hassle tbh <- just pointing out what I felt would be useful in some cases,  but again if its not usual practice, then it's probably best to keep it that way.

**Comment by KilledByAPixel** [comment]
Thank you for your thoughts and suggestions as always. 

1. Yeah, there should be a way to pass an angle into the emitter constructor. I will add that.

2. It would not really be possible to create circular particles without a texture. How would it get a circle shape?

**Comment by slosumo** [comment]
2. Forget about it - I'm still thinking too much in canvas, forgot webgl is dealing with triangles like any engine out there. I assumed there was an arc-like method, but nevermind, need to get used to this - makes all sense to not have one with that in mind :)
