### ISSUE TITLE
Changing debug consts to let?

### ISSUE THREAD

**Issue by slosumo** [KilledByAPixel/LittleJS#27]
Wouldn't it make sense to change debug consts to let, so one can easily enable/disable debug/asserts etc. while trying out the game? It would also allow for debugging of released/live games.

I have my own debugging tools/panel for this, but still some things can be useful (i.e. FPS, objects count), so I don't have to reinvent the wheel for some of those things when I need them.

**Comment by KilledByAPixel** [comment]
No, the whole point of the release build is to remove all the debug stuff and make it small as possible. The debug variables are const 0 in release because this will allow the release minifier to remove all debug code. There is really no reason to use the release build during development other then to check the size. The release build is unlikely to have any significant performance gains and should work the same minus debug features.

However, you can easily just make your own custom build script...

https://github.com/KilledByAPixel/LittleJS/blob/main/build.bat

Just replace "..\engine\engine.all.release.js" with whatever you want. 

You can also have it make custom build of the engine rather then calling engineBuild.bat directly.

**Comment by slosumo** [comment]
Fair points - as a user who doesn't care much about a few extra kB I keep forgetting that is still one of your core goals/points of the engine!
