### ISSUE TITLE
Vector2.normalize() returns (1,0) when used on a zero-length vector (0,0)

### ISSUE THREAD

**Issue by wafflepan** [KilledByAPixel/LittleJS#34]
Normalization of a zero-vector is a degenerate case, since dividing by a magnitude of zero is undefined. The expected outcome in most systems is that the operation should either raise an error, or commonly just return the zero vector itself.

vec2(0,0).normalize() is the specific syntax I've reproduced the issue with.

**Comment by KilledByAPixel** [comment]
Thank you for your perspective. I have actually given a lot of thought on this topic and even use part of it an interview question I sometimes ask engineering candidates.

I've seen many ways different engines handle normalizing a 0 vector and I believe that returning a unit vector is the more correct result because it at half correct, being the correct length. The length part of normalize is not undefined, we know that should always be 1 because it is defined to be a unit vector. It is only the angle that is undefined when normalizing a zero vector.

I believe that triggering an error is not the best solution because normalizing a 0 vector can happen in regular code. So this requires the user to add special checks for that case before calling normalize. In a certain philosophy of game engine I can see how that would be desired, but my goal is to keep things simple. Of course a user can always check if it is a zero vector before calling normalize if that is something that needs special handling.

Returning (0,0) can lead to an interesting situation. Consider the common case where after calling normalize a user calls angle(). Now we must decide again what to do for the angle of a zero vector which is normally undefined. If it is an error that is something the user must handle which I'd like to avoid for reasons stated above. If we return a value like 0, then implicitly defines that the angle of a normalized zero vector as 0.

Thinking about this now, in the philosophy of this game engine, it should return (0,1) when normalizing a zero vector. Because vec2().angle() is 0 and the length of a normalized vector is 1. This implies that normalize should be (0,1) which corresponds to angle 0 which is world up in LittleJS.  I will consider changing it.
